### ISSUE TITLE
PyTorch CUDA works in CLI but not inside QGIS plugin

### ISSUE THREAD

**Issue by arthur048** [opengeos/geoai#458]
Hello, thanks in advance for your help,
Cheers

### Environment Information

-   geoai version:  0.24.0
-   geoai plugin QGIS  version : 0.3.0
-   Python version: 3.12.12
- pytorch-gpu : 2.7.1
- sam3                                  0.1.0.20251211
- segment-geospatial                    1.2.1  

-   Operating System:
Windows 11
NVIDIA GeForce RTX 3060 Laptop GPU (Driver 581.57)
PyTorch 2.7.1 (CUDA 12.8)
QGIS 3.42 via pixi/conda-forge

### Description

When I click "Load Model" with SamGeo3 (SAM3), I get:
"Failed to load model: No CUDA GPUs are available"
However, PyTorch CUDA works fine from the command line using the same pixi environment:

### What I Did

Build with pixi.tolm following geoai tutorial https://opengeoai.org/qgis_plugin/#option-a-windows-with-nvidia-gpu-cuda 

"[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "geo"
platforms = ["linux-64", "win-64"]

[system-requirements]
cuda = "13.0"

[dependencies]
python = "3.12.*"
pytorch-gpu = ">=2.7.1,<3"
qgis = "3.42.*"
geoai = ">=0.24.0"
segment-geospatial = ">=1.2.0"
sam3 = ">=0.1.0.20251211"

```
(base) PS C:\Users\User> cd geo
(base) PS C:\Users\User\geo> pixi run qgis

# PowerShell — works ✓
pixi run python -c "import torch; print(torch.cuda.is_available())"
# True

# QGIS Python console — fails ✗
import torch
torch.cuda.is_available()  # False
torch.cuda.init()  # RuntimeError: No CUDA GPUs are available

```
Both use the same Python environment and torch installation.
I noticed that CUDA_VISIBLE_DEVICES is set to 1 inside the QGIS process (I only have one GPU, index 0). Not sure if this is related or where it comes from.
Any ideas?

<img width="1165" height="553" alt="Image" src="https://github.com/user-attachments/assets/1873aa8a-64af-40f2-a20e-048e28ed724c" />

**Comment by arthur048** [comment]
Hello, 

Thanks for the fixing 3 weeks ago. I just try again and the issue is still there on my side.

I did : 

(base) PS C:\Users\User\geo> pixi update geoai
Environment: default
  ~ C geoai           0.24.0 pyhd8ed1ab_0  ->  0.26.0 pyhd8ed1ab_0
  ~ C geoai-py        0.24.0 pyhd8ed1ab_0  ->  0.26.0 pyhd8ed1ab_0
(base) PS C:\Users\User\geo> pixi run qgis

And still face : 

<img width="357" height="127" alt="Image" src="https://github.com/user-attachments/assets/2326b182-8a86-4b4f-a010-17bbd62eb8cc" />

I runned exactly the same test, cuda available in pixi geo environment, not detected in QGIS with 

# PowerShell — works ✓
pixi run python -c "import torch; print(torch.cuda.is_available())"
# True

# QGIS Python console — fails ✗
import torch
torch.cuda.is_available()  # False
torch.cuda.init()  # RuntimeError: No CUDA GPUs are available

Do you have any idea how can i fix that ? 

Cheers

**Comment by arthur048** [comment]
Hello, 

I fixed my issue by modifying this in QGIS configuration : 

Update(C:/Users/User/AppData/Roaming/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini)
  ⎿  Added 1 line, removed 1 line
      947  customEnvVarsUse=true
      948  max_threads=-1
      949  simplifyAlgorithm=Distance
      **950 -customEnvVars="overwrite|CUDA_VISIBLE_DEVICES=1", "overwrite|OCL_DEVICE_TYPE=GPU", "overwrite|GDAL_USE_OPENCL=YES"
      950 +customEnvVars="overwrite|CUDA_VISIBLE_DEVICES=0", "overwrite|OCL_DEVICE_TYPE=GPU", "overwrite|GDAL_USE_OPENCL=YES"**
      951  map_update_interval=250
      952  simplifyDrawingTol=1
      953  magnifier_factor_default=1

Cheers,
